site_name: API Solidária de Doações
theme:
  name: readthedocs

nav:
  - Início: index.md
  - Apresentação: apresentacao.md
  - Tecnologias: tecnologias.md
  - Hospedagem: hospedagem.md
  - Integrantes: integrantes.md
